export class User {
  constructor(
    public fullname: string,
    public username: string,
    public password: string,
    public guardianType: string,
    public guardianName: string,
    public address: string,
    public citizenship: string,
    public state: string,
    public country: string,
    public emailAddress: string,
    public gender: string,
    public maritalStatus: string,
    public contactNo: number,
    public dob: Date,
    public registrationDate: Date,
    public accountType: string,
    public branchName: string,
    public citizenStatus: string,
    public amount: number,
    public idProofType: string,
    public idDocNo: string,
    public acHolderName: string,
    public acHolderAccNo: string,
    public acHolderAddr: string,
    public accountNumber: string,
    public customerId: string,
    public bankName: string
  ) {}
}
